src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $en_vente = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function isEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): static
    {
        $this->en_vente = $en_vente;

        return $this;
    }
}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('modele')
            ->add('description')
            ->add('date_creation')
            ->add('image')
            ->add('en_vente')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/vehicule')]
class VehiculeController extends AbstractController
{
    #[Route('/', name: 'app_vehicule_index', methods: ['GET'])]
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        return $this->render('vehicule/index.html.twig', [
            'vehicules' => $vehiculeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_vehicule_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vehicule = new Vehicule();
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vehicule);
            $entityManager->flush();

            return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vehicule/new.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vehicule_show', methods: ['GET'])]
    public function show(Vehicule $vehicule): Response
    {
        return $this->render('vehicule/show.html.twig', [
            'vehicule' => $vehicule,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_vehicule_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vehicule/edit.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vehicule_delete', methods: ['POST'])]
    public function delete(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicule->getId(), $request->request->get('_token'))) {
            $entityManager->remove($vehicule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vehicule/_delete_form.html.twig
<form method="post" action="{{ path('app_vehicule_delete', {'id': vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vehicule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vehicule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vehicule{% endblock %}

{% block body %}
    <h1>Edit Vehicule</h1>

    {{ include('vehicule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vehicule_index') }}">back to list</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}

templates/vehicule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule index{% endblock %}

{% block body %}
    <h1>Vehicule index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Modele</th>
                <th>Description</th>
                <th>Date_creation</th>
                <th>Image</th>
                <th>En_vente</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vehicule in vehicules %}
            <tr>
                <td>{{ vehicule.id }}</td>
                <td>{{ vehicule.nom }}</td>
                <td>{{ vehicule.modele }}</td>
                <td>{{ vehicule.description }}</td>
                <td>{{ vehicule.dateCreation ? vehicule.dateCreation|date('Y-m-d') : '' }}</td>
                <td>{{ vehicule.image }}</td>
                <td>{{ vehicule.enVente ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_vehicule_show', {'id': vehicule.id}) }}">show</a>
                    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_new') }}">Create new</a>
{% endblock %}

templates/vehicule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vehicule{% endblock %}

{% block body %}
    <h1>Create new Vehicule</h1>

    {{ include('vehicule/_form.html.twig') }}

    <a href="{{ path('app_vehicule_index') }}">back to list</a>
{% endblock %}

templates/vehicule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule{% endblock %}

{% block body %}
    <h1>Vehicule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicule.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ vehicule.nom }}</td>
            </tr>
            <tr>
                <th>Modele</th>
                <td>{{ vehicule.modele }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ vehicule.description }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ vehicule.dateCreation ? vehicule.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ vehicule.image }}</td>
            </tr>
            <tr>
                <th>En_vente</th>
                <td>{{ vehicule.enVente ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_index') }}">back to list</a>

    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}">edit</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}